# Generated by Django 3.2.6 on 2021-08-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
    ]
