# Generated by Django 3.2.6 on 2021-08-12 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210812_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revendedor',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='revendedor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user'),
            preserve_default=False,
        ),
    ]
