# Generated by Django 3.2.6 on 2021-08-12 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210812_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.revendedor')),
            ],
        ),
    ]
