# Generated by Django 3.2.6 on 2021-08-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
