# Generated by Django 3.2.6 on 2021-08-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_compra_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em Validacao'), (2, 'Aprovado'), (3, 'Nao Aprovado')], default=1),
        ),
    ]
