# Generated by Django 3.2.6 on 2021-08-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_compra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
    ]
